# 分析代码
name: Clang-Tidy Checking

# 设置触发器
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # 在linux下构建
  linux-build:
    # 使用最新ubuntu镜像
    runs-on: ubuntu-latest

    steps:
    # 签出代码
    - uses: actions/checkout@v2

    # 执行检查脚本
    - name: clang-tidy checking
      run: python ./build.py debug && python3 ./script/run-clang-tidy.py -j 12 -p ./build ./src/* && python3 ./script/run-clang-tidy.py -j 12 -p ./build ./test/*
      
    